import React from 'react'
export const ImagePath = {
    Home_Image : require("./../../assets/Home.png"),
    Bill_History: require("./../../assets/BillHistory.png"),
    Complaints: require("./../../assets/Complaint.png"),
    Support: require("./../../assets/Support.png"),
    More: require("./../../assets/More.png"),
    Profile: require("./../../assets/Profile.png"),
    Flag: require("./../../assets/Flag.png"),
    Notification: require("./../../assets/Notification.png"),
    Line: require("./../../assets/Line.png"),
    DownArrow: require("./../../assets/Down.png"),
    RightArrow: require("./../../assets/RightArrow.png"),
    Payment: require("./../../assets/Payment.png"),
    ContactUs: require("./../../assets/ContactUs.png"),
    FQA: require("./../../assets/FQA.png"),
    Find: require("./../../assets/Find.png"),
    Notification_Light: require("./../../assets/Notification-Light.png"),
    Logo: require("../../assets/Logo.png"),
    SliderLogo: require("../../assets/SliderLogo.png"),
    FilterIcon: require("../../assets/FilterIcon.png"),
    LeftArrow: require("../../assets/LeftArrow.png"),
    FlatLine: require("../../assets/FlatLine.png"),
    Share: require("../../assets/Share.png"),
    DotLines: require("../../assets/DotLines.png"),
    Complaint: require("../../assets/Complaints.png"),
    PlusIcon: require("../../assets/Plus.png"),
    RoundLeftArrow: require("../../assets/RoundLeftArrow.png"),
    RoundRightArrow: require("../../assets/RoundRightArrow.png"),
    Left: require("../../assets/Left.png"),
    PaymentHistory: require("../../assets/PaymentHistory.png")
} 